### ISSUE TITLE
[FEATURE] Hide all unnecessary information

### ISSUE THREAD

**Issue by MomentQYC** [truemail-rb/truemail-rack#105]
### New feature request checklist

- [x] I have updated `truemail-rack` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-rack/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-rack)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-rack/issues)

### Feature description

Add an explicitly settable debug mode, hide all unnecessary information in non-debug mode, including debugging information, configuration content, etc.

**Comment by bestwebua** [comment]
Hi, @MomentQYC! Thanks for suggestion but I guess that for this service all provided information is necessary.
