### ISSUE TITLE
"resource not found" across wide range of hosting environments

### ISSUE THREAD

**Issue by gregwbrooks** [truemail-rb/truemail-rack#24]
### New Issue Checklist

- [X] I have updated truemail to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-rack/blob/master/CONTRIBUTING.md)
- [X] I have read the [documentation](https://github.com/truemail-rb/truemail-rack/blob/master/README.md)
- [X] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-rack/issues)

### Issue Description

The Docker image of Truemail-rack mounts properly in a range of environments -- Plesk, Cyberpanel, Portainer, etc.. However, all attempts to use it from the command line fail with "error":"resource not found".

This occurs via HTTPS or HTTP. (Attempts to secure the subdomain via SSL report back as successful but HTTPS connections to the API always fail.) It occurs on a single-host box with one domain, trying to access the API with a single verification test via a browser using either the domain or the IP in the URL. It occurs when trying to use the default port of 9292 or when a management app like Portainer assigns a random IP.

I suspect this is user/installer error rather than a problem with Truemail, but I wanted to report the difficulty in hope of guidance.

Example URLs that create this error:

<pre>
https://validator.domain.com/api/v1/verify/status?access_token={api-key}&email_id={email}

https://validator.domain.com:{assigned-port}/api/v1/verify/single?address_info=1&timeout=100&access_token={API-key}&email={email}
</pre>

##### Complete output when running truemail, including the stack trace and command used

<details>
  <pre>{"error":"resource not found"}</pre>
</details>

**Comment by bestwebua** [comment]
Hi, @gregwbrooks ! Thanks for your report. It's seems like you trying to use not existent (invalid) Truemail server endpoint. Your validator urls should look like as in example below:
```code
http://validator.domain.com:{assigned-port}/?email=your@email.here
https://validator.domain.com:{assigned-port}/?email=your@email.here
http://validator.domain.com:{assigned-port}/healthcheck
```
You should use [correct Truemail endpoits](https://github.com/truemail-rb/truemail-rack#requestresponse-example) to get succesful request.

**Comment by bestwebua** [comment]
Also you can enable log all http requests to stdout.
Just add in your `docker-compose.yml` in envirinment section `LOG_STDOUT: 'true'`
It will help you to debug what endpoints you exactly trying to use. Anyway let me know about your result in this thread. Cheers.

<img width="847" alt="Screenshot 2020-09-24 at 10 32 26 PM" src="https://user-images.githubusercontent.com/14002692/94191190-d556e980-feb5-11ea-8d2f-f698f01dbb13.png">

**Comment by gregwbrooks** [comment]
@bestwebua thanks for the helpful reply. Unfortunately, no combination of things I've tried gets me past "{"error":"invalid truemail access token"}". As I said initially, this is 99% likely a case of error on my part rather than an issue with Truemail.

I suspect I'll end up hiring someone to sort it out -- it really does seem like an ideal solution for my use case. Thanks.
