### ISSUE TITLE
[BUG] UndefinedConversionError when submitting certain emails

### ISSUE THREAD

**Issue by eni9889** [truemail-rb/truemail-rack#31]
When I try to parse this email:

```
abigayle123phil%40gnail.com
```

I am getting:

```
Encoding::UndefinedConversionError: "\xD3" from ASCII-8BIT to UTF-8
```

**Comment by bestwebua** [comment]
Please, use presetted templates when you add new issues. Could you provide stacktrace with error.

**Comment by eni9889** [comment]
Sorry about that will do in the future.

This is all I see: 

```
2020-12-02 14:46:47 +0000 Rack app ("GET /email=andersontyesha1@gnail.com" - (64.53.249.254, 162.158.75.197)): #<Encoding::UndefinedConversionError: "\xD3" from ASCII-8BIT to UTF-8>
```

**Comment by bestwebua** [comment]
So you have changed app dependencies and have got this error because in your case params were not decoded.

**Comment by bestwebua** [comment]
@eni9889, I can't reproduce this failure... Could you provide more details?
<img width="765" alt="Screenshot 2020-12-02 at 9 57 59 PM" src="https://user-images.githubusercontent.com/14002692/100924638-9498d380-34e9-11eb-8ad2-ba05c96534e9.png">

**Comment by eni9889** [comment]
This is running on ubuntu 18 and using version 0.2.6 of the server with ruby 2.6.5

Config is:
```
RAILS_ENV=development \
SMTP_SAFE_CHECK=true \
LOG_STDOUT=true \
VERIFIER_EMAIL="..." \
ACCESS_TOKENS=... \
/root/.rbenv/bin/rbenv exec puma -w 2 -t 0:16 --port 8080
```

**Comment by bestwebua** [comment]
What the rails?

**Comment by eni9889** [comment]
@bestwebua that's a typo, it should not affect anything but I can take it out.

**Comment by bestwebua** [comment]
Try values from my example and tell about your result

**Comment by eni9889** [comment]
abigayle123phil@gnail.co works but abigayle123phil@gnail.com does not, which makes me think this is an error when parsing the SMTP server response

**Comment by bestwebua** [comment]
@eni9889, yeah! I got it. It's not Truemail Server issue. It happened because can't to process hash with some national chars to json in validator result serializer:

```ruby
{:rcptto=>"550 mailbox abigayle123phil@gnail.com unavailable (\xD3\xCA\xCF\xE4\xB2\xBB\xB4\xE6\xD4\xDA)\n"}.to_json
# => JSON::GeneratorError: source sequence is illegal/malformed utf-8
```
I'm going to fix it tommorow in core lib. Cheers!
