### ISSUE TITLE
[QUESTION] How to use SMTP which requires authentication from localhost?

### ISSUE THREAD

**Issue by shrestsav** [truemail-rb/truemail-rack#96]
### New question checklist

- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-rack/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-rack)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-rack/issues)

### Question
How to use SMTP which requires authentication from localhost?

My SMTP mail server requires authentication, so how do I configure this?

**Comment by bestwebua** [comment]
Hi, @shrestsav! Thanks for your question. No, it works only with SMTP servers without authentication.

**Comment by shrestsav** [comment]
@bestwebua isn't that a big security issue, and won't my server IP get blocked from gmail, yahoo, etc if I were to verify thousands of emails a day

**Comment by bestwebua** [comment]
@shrestsav It's another big topic outside of this tool scope.
